"""Nonpartisan heuristic copy for the Dual Lens panel (no external AI)."""

from __future__ import annotations

from vault.models import CivicItem


def dual_lens_for_item(item: CivicItem) -> dict[str, str]:
    """Balanced placeholder perspectives; replace with real model output later."""
    lead = (item.title[:100] + ("…" if len(item.title) > 100 else "")).strip() or "this signal"

    if item.kind == "legislation":
        supporters = (
            "Supporters often argue the proposal improves accountability, closes gaps in current law, "
            f"and delivers clearer rules or resources tied to: “{lead}”. "
            "They tend to emphasize measurable benefits for constituents and timely action."
        )
        critics = (
            "Critics frequently stress implementation risk, fiscal tradeoffs, or uneven effects—"
            f"especially whether “{lead}” moves too fast, bundles unrelated provisions, "
            "or underestimates compliance burdens on people and organizations."
        )
    else:
        supporters = (
            "Sympathetic framings usually highlight public interest, reform momentum, or documented harms—"
            f"using stories like “{lead}” to argue attention or policy change is warranted."
        )
        critics = (
            "Skeptical framings often raise uncertainty in evidence, incentives in who benefits, "
            f"or whether narratives around “{lead}” oversimplify tradeoffs and downstream effects."
        )

    return {"supporters": supporters, "critics": critics, "disclaimer": "Heuristic preview — not generated by an external AI."}
